version: "3"
  
services: 
  reactapp:       #image name
    stdin_open: true             #for opening (-it) flag in container  
    tty: true                    #for opening (-it) flag in container
    build: .
    ports:
      - "80:8080"
    volumes:
      - ./src:/app/src:ro
      

# docker-compose up -d --build              ---------- to make a new build  with compose